#!/bin/bash
#backup files to dir
backtoDir="/home/mindfine/Yunio/backup"
gitdir="/home/mindfine/git/dataswitch/backup/"
comment=$1
echo "-------------------------------------------------------------"
echo "---backup is running---"

#compressing files to single 7zip file
#end with space character and an escape char'\' to escape the return character. and this will add multi files.
function compressAndMove
{
	mkdir -p $backtoDir
	zip -r $backtoDir/linux-mint-homedir-backup-`date -d today +"%Y-%m-%d-%H-%M-%S"`.zip \
/home/mindfine/bin/* \
/etc/environment \
/etc/udev/rules.d/50-android.rules \
-x \
/home/mindfine/bin/blender \
/home/mindfine/bin/blenderplayer \
/home/mindfine/bin/ffplay \
/home/mindfine/bin/ffprobe \
/home/mindfine/bin/ffserver \
/home/mindfine/bin/shank \
/home/mindfine/bin/ffmpeg \
/home/mindfine/bin/adb \
/home/mindfine/bin/x264 \
/home/mindfine/bin/mtpfs
}
#compressAndMove

files=(\
/home/mindfine/bin \
/etc/environment \
/home/mindfine/.m2/settings.xml \
/etc/fonts/conf.avail/69-language-selector-zh-cn.conf \
/etc/fonts/conf.avail/69-language-selector-zh-mo.conf \
/home/mindfine/.bashrc \
/home/mindfine/.android/adb_usb.ini \
/home/.android/adb_usb.ini \
/etc/udev/rules.d/51-android.rules \
/home/mindfine/.bash_history)
#put this to git if can.
function putToGit
{
	cd $gitdir
	echo "---location:"`pwd`
	rm -r *
	for filee in ${files[*]}
	do
		#cp -v --parents $filee $gitdir
		rsync -av \
--exclude='blender' \
--exclude='bluegriffon' \
--exclude='blenderplayer' \
--exclude='ffplay' \
--exclude='ffprobe' \
--exclude='ffserver' \
--exclude='shank' \
--exclude='ffmpeg' \
--exclude='adb' \
--exclude='x264' \
--exclude='mtpfs' \
--exclude='eclipse' \
--exclude='mvnDebug' \
--exclude='*.log' \
--exclude='*.swp' \
$filee $gitdir
	done
	cd $gitdir
	cd ..
	echo "---location:"`pwd`
	echo "---delete all files from cached index---"
	git rm -r * --cached
	git status
	git add .
	if [ -z "$comment" ]
	then
		comment="auto commit by backup"
	fi
	git commit -m "$comment`date -d today +"-%Y-%m-%d-%H-%M-%S"`"
	git push
}
putToGit

