#!/usr/bin/env bash

# author: rankun203@gmail.com

from=/storage/sdcard0/DCIM/Camera/
v=0.5

if [[ "$1" == "-p" ]]
then
  from=$2  
  else if [[ "$1" == "-h" ]]
  then
    echo "importPhotos v$v"
    echo "This script is use to import photos from your phone."
    echo "You can also use custom path."
    echo "----"  
    echo "usage:"
    echo "importPhotos"
    echo "importPhotos -p /storage/sdcard0/DCIM/"
    echo "importPhotos -h"
    exit
  fi
fi

echo "> Import from: $from"

mkdir -p ~/tmp/dcim

echo "> Pull all the photos from my Phone?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) echo '> Pulling'; adb pull $from ~/tmp/dcim; echo '> Done';  break;;
        No ) exit;;
    esac
done
echo ''


echo 'Delete all photos on phone?'

select yn in "Yes" "No"; do
    case $yn in
        Yes ) echo '> Deleting'; adb shell "rm -r /storage/sdcard0/DCIM/Camera/"; echo '> Deleted'; break;;
        No ) exit;;
    esac
done
echo ''


echo 'Import them to iPhoto(Close iPhoto after import finished to continue.)?'

select yn in "Yes" "No"; do
    case $yn in
        Yes ) echo '> Opening iPhoto'; open -Wa iPhoto ~/tmp/dcim/*; echo '> Imported'; break;;
        No ) exit;;
    esac
done
echo ''

echo 'Deleting import cache from ~/tmp/dcim'
rm -rf ~/tmp/dcim/*;
echo '> Deleted';

exit 1

