#!/usr/bin/env bash

container=67f7536f1a37
password=hello
localport=44444

function usage {
  cat <<UsageHERE
mysqll start|stop|init
UsageHERE
}
function init {
  docker start -d -p $localport:3306 -e MYSQL_ROOT_PASSWORD=$password $container
  # update this script's container name.
}

function start {
  docker start $container
}

function stop {
  docker stop $container
}

if [ $# -eq 0 ]
then
  exit 1

elif [ "$1" = "start" ]
then
  start
  exit 0

elif [ "$1" = "stop" ]
then
  stop
  exit 0

elif [ "$1" = "init" ]
then
  init
  exit 0

else
  usage
fi

exit $?
