#!/usr/bin/perl -w
use strict;
use warnings;

### Start CONFIG

my $searchPath = '/home/rankun203/Pictures/GoogleNowPictures';                               # <- DON'T FORGET TO CHANGE THAT !!!
my $switchTime = 600;                 # Time is in seconds

### END CONFIG

# bgotd-- background of the day
#
# A super simple script which randomly picks a jpg/JPG/jpeg/JPEG photo to place as your
# Gnome desktop.
#
# Written by Michael Moore, Nov. 2007
# This work is hereby placed in the public domain 

#my @photos = `find $searchPath -type f | grep [jJ][pP][eE]*[gG]`;
my @photos = `find $searchPath -type f | grep [pP][nN][gG]`;
chomp(@photos);
my $photo;

while(1)
{
    $photo = $photos[rand($#photos)];
    `gsettings set org.gnome.desktop.background picture-uri "file:///$photo"`;
    sleep($switchTime);
}
